version: '3.8'

services:
  filesync-test:
    image: open-webui-filesync:test
    container_name: filesync-test
    ports:
      - "8001:8000"
    environment:
      OPENWEBUI_URL: http://test:8080
      OPENWEBUI_API_KEY: test_key
      WEB_PORT: 8000
      WEB_HOST: 0.0.0.0
    volumes:
      - ./test_files:/data:ro
      - ./test_config:/app/config
      - ./test_state:/app/state
